{
	"version": 1549635964,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btngoogleplay-sheet0.png",
		"images/btnaddsite-sheet0.png",
		"images/btnvideo-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btnkiz10-sheet0.png",
		"images/btnmore-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnback-sheet0.png",
		"images/btnbuygold-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnshopgold-sheet0.png",
		"images/btnlevel-sheet0.png",
		"images/btnlevel-sheet1.png",
		"images/btnshop-sheet0.png",
		"images/btnupgrade-sheet0.png",
		"images/btnselect-sheet0.png",
		"images/btnbait-sheet0.png",
		"images/btnbait-sheet1.png",
		"images/btnnets-sheet0.png",
		"images/btnnets-sheet1.png",
		"images/btnmine-sheet0.png",
		"images/btnmine-sheet1.png",
		"images/bgbird-sheet0.png",
		"images/bgcloud-sheet0.png",
		"images/bgfishercat-sheet0.png",
		"images/bgmainmenu-sheet0.png",
		"images/bgripple-sheet0.png",
		"images/bg1-sheet0.png",
		"images/bgback1-sheet0.png",
		"images/bgfront1-sheet0.png",
		"images/bgripple1-sheet0.png",
		"images/bgplant11-sheet0.png",
		"images/bgplant21-sheet0.png",
		"images/bgplant31-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bgback2-sheet0.png",
		"images/bgfront2-sheet0.png",
		"images/bgripple2-sheet0.png",
		"images/bgfog-sheet0.png",
		"images/bg3-sheet0.png",
		"images/bgback3-sheet0.png",
		"images/bgfront3-sheet0.png",
		"images/bgripple3-sheet0.png",
		"images/bgplant13-sheet0.png",
		"images/bgplant23-sheet0.png",
		"images/bgplant33-sheet0.png",
		"images/txtgold.png",
		"images/txthighscore.png",
		"images/txtstatic.png",
		"images/txtoxygen.png",
		"images/txtwave.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/labelresult-sheet0.png",
		"images/labelscore-sheet0.png",
		"images/labelbest-sheet0.png",
		"images/labelnew-sheet0.png",
		"images/resultshine-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr1024x450-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/uigold-sheet0.png",
		"images/flashwhite-sheet0.png",
		"images/flashred-sheet0.png",
		"images/bgbubble1-sheet0.png",
		"images/bgbubble2-sheet0.png",
		"images/bgbubble2-sheet1.png",
		"images/foption-sheet0.png",
		"images/uioxygen-sheet0.png",
		"images/oxygen-sheet0.png",
		"images/oxygenmask-sheet0.png",
		"images/labelwave-sheet0.png",
		"images/pointerwave-sheet0.png",
		"images/uiwave-sheet0.png",
		"images/uifish-sheet0.png",
		"images/combo-sheet0.png",
		"images/combo-sheet1.png",
		"images/combo-sheet2.png",
		"images/combobarbg-sheet0.png",
		"images/combobar-sheet0.png",
		"images/game-sheet0.png",
		"images/rope-sheet0.png",
		"images/target-sheet0.png",
		"images/target-sheet1.png",
		"images/gold-sheet0.png",
		"images/warning-sheet0.png",
		"images/enemy0-sheet0.png",
		"images/enemy0-sheet1.png",
		"images/enemy1-sheet0.png",
		"images/enemy1-sheet1.png",
		"images/enemy2-sheet0.png",
		"images/enemy2-sheet1.png",
		"images/enemy3-sheet0.png",
		"images/enemy3-sheet1.png",
		"images/enemy4-sheet0.png",
		"images/enemy4-sheet1.png",
		"images/enemy5-sheet0.png",
		"images/enemy5-sheet1.png",
		"images/enemy6-sheet0.png",
		"images/enemy6-sheet1.png",
		"images/enemy7-sheet0.png",
		"images/enemy7-sheet1.png",
		"images/enemy8-sheet0.png",
		"images/enemy8-sheet1.png",
		"images/enemy9-sheet0.png",
		"images/enemy9-sheet1.png",
		"images/enemy10-sheet0.png",
		"images/enemy10-sheet1.png",
		"images/enemy11-sheet0.png",
		"images/enemy11-sheet1.png",
		"images/enemy-sheet0.png",
		"images/fish0-sheet0.png",
		"images/fish0-sheet1.png",
		"images/fish0-sheet2.png",
		"images/fish1-sheet0.png",
		"images/fish1-sheet1.png",
		"images/fish1-sheet2.png",
		"images/fish2-sheet0.png",
		"images/fish2-sheet1.png",
		"images/fish2-sheet2.png",
		"images/fish3-sheet0.png",
		"images/fish3-sheet1.png",
		"images/fish3-sheet2.png",
		"images/fish-sheet0.png",
		"images/fish-sheet1.png",
		"images/fish-sheet2.png",
		"images/fish6-sheet0.png",
		"images/fish6-sheet1.png",
		"images/fish6-sheet2.png",
		"images/fish7-sheet0.png",
		"images/fish7-sheet1.png",
		"images/fish7-sheet2.png",
		"images/fish8-sheet0.png",
		"images/fish8-sheet1.png",
		"images/fish8-sheet2.png",
		"images/fish9-sheet0.png",
		"images/fish9-sheet1.png",
		"images/fish9-sheet2.png",
		"images/fish4-sheet0.png",
		"images/fish4-sheet1.png",
		"images/fish4-sheet2.png",
		"images/fish5-sheet0.png",
		"images/fish5-sheet1.png",
		"images/fish5-sheet2.png",
		"images/fish10-sheet0.png",
		"images/fish10-sheet1.png",
		"images/fish10-sheet2.png",
		"images/fish11-sheet0.png",
		"images/fish11-sheet1.png",
		"images/fish11-sheet2.png",
		"images/charbody-sheet0.png",
		"images/charhead-sheet0.png",
		"images/charhead-sheet1.png",
		"images/charnets-sheet0.png",
		"images/charweapon-sheet0.png",
		"images/charweapon-sheet1.png",
		"images/charweapon-sheet2.png",
		"images/vfxcharonfloor-sheet0.png",
		"images/vfxcharonfloor-sheet1.png",
		"images/vfxhitenemy-sheet0.png",
		"images/vfxpowupshine-sheet0.png",
		"images/vfxpowupget-sheet0.png",
		"images/vfxpowupget-sheet1.png",
		"images/vfxlightning-sheet0.png",
		"images/vfxlightning-sheet1.png",
		"images/vfxgold-sheet0.png",
		"images/vfxgold-sheet1.png",
		"images/vfxcombo.png",
		"images/bullet0-sheet0.png",
		"images/bullet1-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/bullet3-sheet0.png",
		"images/chain-sheet0.png",
		"images/chaintail-sheet0.png",
		"images/powupbait-sheet0.png",
		"images/powupnets-sheet0.png",
		"images/powupmine-sheet0.png",
		"images/bait-sheet0.png",
		"images/baitparticles.png",
		"images/mine-sheet0.png",
		"images/mine-sheet1.png",
		"images/mine-sheet2.png",
		"images/nets-sheet0.png",
		"images/ropenets.png",
		"images/uibuygold-sheet0.png",
		"images/fshopgold-sheet0.png",
		"images/uititle-sheet0.png",
		"images/uilevel-sheet0.png",
		"images/fupgrade-sheet0.png",
		"images/uiupgradeweapon-sheet0.png",
		"images/uiupgradelevel-sheet0.png",
		"images/uiupgradelevel-sheet1.png",
		"images/uiupgrade-sheet0.png",
		"images/uiupgradepadlock-sheet0.png",
		"images/uiupgradegold-sheet0.png",
		"images/uitutorial-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/not enough gold.m4a",
		"media/not enough gold.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/bullet.m4a",
		"media/bullet.ogg",
		"media/char fall.m4a",
		"media/char fall.ogg",
		"media/char falling into water.m4a",
		"media/char falling into water.ogg",
		"media/char land.m4a",
		"media/char land.ogg",
		"media/enemy die.m4a",
		"media/enemy die.ogg",
		"media/electrocuted.m4a",
		"media/electrocuted.ogg",
		"media/mine.m4a",
		"media/mine.ogg",
		"media/damage.m4a",
		"media/damage.ogg",
		"media/pick item.m4a",
		"media/pick item.ogg",
		"media/rope nets.m4a",
		"media/rope nets.ogg",
		"media/spark electric.m4a",
		"media/spark electric.ogg",
		"media/throw bait.m4a",
		"media/throw bait.ogg",
		"media/throw mine.m4a",
		"media/throw mine.ogg",
		"media/water flow.m4a",
		"media/water flow.ogg",
		"media/absorb.m4a",
		"media/absorb.ogg",
		"media/power up actived.m4a",
		"media/power up actived.ogg",
		"media/char pulled up.m4a",
		"media/char pulled up.ogg",
		"media/combo.m4a",
		"media/combo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}