{
	"version": 1581498073,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/preloaderbackground-sheet0.png",
		"images/preloaderloading-sheet0.png",
		"images/buttonspecialattackbackground1-sheet0.png",
		"images/buttonspecialattackbackground2-sheet0.png",
		"images/buttonspecialattackbackground3-sheet0.png",
		"images/buttonupgradehero-sheet0.png",
		"images/buttonupgradehero-sheet1.png",
		"images/buttonupgradeturret-sheet0.png",
		"images/buttonupgradeturret-sheet1.png",
		"images/buttongoldshop-sheet0.png",
		"images/buttongoldshop-sheet1.png",
		"images/buttonbackmainmenu-sheet0.png",
		"images/buttonnextstage-sheet0.png",
		"images/buttonupgradeherolevel-sheet0.png",
		"images/buttongoldbuy-sheet0.png",
		"images/buttonprev-sheet0.png",
		"images/buttonnext-sheet0.png",
		"images/buttonplay-sheet0.png",
		"images/buttonmoregames-sheet0.png",
		"images/buttonhome-sheet0.png",
		"images/buttonretry-sheet0.png",
		"images/buttonkiz10-sheet0.png",
		"images/buttonwalkthrough-sheet0.png",
		"images/buttongoogleplay-sheet0.png",
		"images/buttonaddtoyoursite-sheet0.png",
		"images/buttonresetdata-sheet0.png",
		"images/buttonmusic-sheet0.png",
		"images/buttonsound-sheet0.png",
		"images/buttonresume-sheet0.png",
		"images/buttonoption-sheet0.png",
		"images/buttonno-sheet0.png",
		"images/buttonyes-sheet0.png",
		"images/mainmenutitle-sheet0.png",
		"images/mainmenutitledefender-sheet0.png",
		"images/mainmenutitlewingleft-sheet0.png",
		"images/mainmenutitlewingright-sheet0.png",
		"images/mainmenuwave-sheet0.png",
		"images/mainmenuresetdatacontent-sheet0.png",
		"images/mainmenuresetdataframe-sheet0.png",
		"images/border1-sheet0.png",
		"images/border2-sheet0.png",
		"images/flash-sheet0.png",
		"images/objectposition-sheet0.png",
		"images/center-sheet0.png",
		"images/menuoverlay-sheet0.png",
		"images/gatetop-sheet0.png",
		"images/gatebottom-sheet0.png",
		"images/gatetopnova-sheet0.png",
		"images/gatebottomdefender-sheet0.png",
		"images/gatetitle-sheet0.png",
		"images/flashwalldestroy-sheet0.png",
		"images/optionframe-sheet0.png",
		"images/resultframewin-sheet0.png",
		"images/resultframelose-sheet0.png",
		"images/resultlight-sheet0.png",
		"images/resulttextreward-sheet0.png",
		"images/resulttextkillbonus-sheet0.png",
		"images/resulttexttotal-sheet0.png",
		"images/resultgold-sheet0.png",
		"images/textresultreward.png",
		"images/debug.png",
		"images/textwave.png",
		"images/textgold.png",
		"images/textheroupgrade.png",
		"images/textwalllife.png",
		"images/textupgradeincrease.png",
		"images/textupgradelevel.png",
		"images/textgoldincrease.png",
		"images/backgroundgame-sheet0.png",
		"images/street-sheet0.png",
		"images/backgroundgame2-sheet0.png",
		"images/wall-sheet0.png",
		"images/framebackground-sheet0.png",
		"images/key1-sheet0.png",
		"images/key2-sheet0.png",
		"images/key3-sheet0.png",
		"images/barbossbackground-sheet0.png",
		"images/barwallbackground-sheet0.png",
		"images/barboss-sheet0.png",
		"images/barwall-sheet0.png",
		"images/barspecialattack-sheet0.png",
		"images/pointgold-sheet0.png",
		"images/pointstage-sheet0.png",
		"images/enemyboss-sheet0.png",
		"images/enemyboss-sheet1.png",
		"images/enemybosscollision-sheet0.png",
		"images/enemybosspoison-sheet0.png",
		"images/enemybosspoison-sheet1.png",
		"images/enemybosspoison-sheet2.png",
		"images/enemybosspoisoncollision-sheet0.png",
		"images/enemyinfecman-sheet0.png",
		"images/enemyinfecmancollision-sheet0.png",
		"images/enemykingbat-sheet0.png",
		"images/enemykingbat-sheet1.png",
		"images/enemykingbatpoison-sheet0.png",
		"images/enemykingbatcollision-sheet0.png",
		"images/enemykingbatpoisoncollision-sheet0.png",
		"images/enemykingbatshadow-sheet0.png",
		"images/enemyspiderbomb-sheet0.png",
		"images/enemyspiderbomb-sheet1.png",
		"images/enemyspiderbombcollision-sheet0.png",
		"images/enemyvoidarmor-sheet0.png",
		"images/enemyvoidarmor-sheet1.png",
		"images/enemyvoidarmorcollision-sheet0.png",
		"images/enemyvoidarmorpoison-sheet0.png",
		"images/enemyvoidarmorpoisoncollision-sheet0.png",
		"images/enemyvoidarmy-sheet0.png",
		"images/enemyvoidarmy-sheet1.png",
		"images/enemyvoidarmycollision-sheet0.png",
		"images/enemyvoidblood-sheet0.png",
		"images/enemyvoidblood-sheet1.png",
		"images/enemyvoidbloodcollision-sheet0.png",
		"images/enemyvoidleader-sheet0.png",
		"images/enemyvoidleader-sheet1.png",
		"images/enemyvoidleader-sheet2.png",
		"images/enemyvoidleadercollision-sheet0.png",
		"images/enemybloodanimation-sheet0.png",
		"images/enemybloodanimation-sheet1.png",
		"images/enemybloodpath-sheet0.png",
		"images/bloodboss1-sheet0.png",
		"images/bloodboss2-sheet0.png",
		"images/blood1-sheet0.png",
		"images/blood2-sheet0.png",
		"images/blood3-sheet0.png",
		"images/blood4-sheet0.png",
		"images/blood5-sheet0.png",
		"images/enemymargin-sheet0.png",
		"images/enemyeffectdamage-sheet0.png",
		"images/enemyeffectdamage-sheet1.png",
		"images/enemyeffectdamage-sheet2.png",
		"images/enemypoisonexplosion-sheet0.png",
		"images/enemypoisonexplosion-sheet1.png",
		"images/enemydie-sheet0.png",
		"images/defendergunnerbody-sheet0.png",
		"images/defendergunnerhead-sheet0.png",
		"images/defendergunnershot-sheet0.png",
		"images/defendergunnereffect1-sheet0.png",
		"images/defendergunnereffect2-sheet0.png",
		"images/defendergunnereffect2-sheet1.png",
		"images/defendergunnereffect2-sheet2.png",
		"images/defendergunnerbullet-sheet0.png",
		"images/defenderplasmagunbottom-sheet0.png",
		"images/defenderplasmagunshot-sheet0.png",
		"images/defenderplasmagunhead-sheet0.png",
		"images/defenderplasmagunlaser-sheet0.png",
		"images/defenderplasmaguneffect-sheet0.png",
		"images/defendercannonfront-sheet0.png",
		"images/defendercannonback-sheet0.png",
		"images/defendercannonshot-sheet0.png",
		"images/defendercannonmissile-sheet0.png",
		"images/defendercannoneffect-sheet0.png",
		"images/defendercannoneffect-sheet1.png",
		"images/defendercannonmissileeffect1-sheet0.png",
		"images/specialattackrocket-sheet0.png",
		"images/specialattackrocketeffect-sheet0.png",
		"images/specialattackrocketexplosion-sheet0.png",
		"images/specialattackrocketexplosion-sheet1.png",
		"images/specialattacklaser-sheet0.png",
		"images/specialattacklasereffect-sheet0.png",
		"images/specialattacktrap-sheet0.png",
		"images/specialattacktrapeffect1-sheet0.png",
		"images/specialattacktrapeffect2-sheet0.png",
		"images/specialattacktrapeffect2-sheet1.png",
		"images/damageareacollision-sheet0.png",
		"images/overlay-sheet0.png",
		"images/specialattackhole-sheet0.png",
		"images/explosioneffectenemy-sheet0.png",
		"images/explosioneffectenemyboss-sheet0.png",
		"images/preingameherotext-sheet0.png",
		"images/preingameherotextlevelattackspeed-sheet0.png",
		"images/preingameherotextlevelbullet-sheet0.png",
		"images/preingameherotextleveldamage-sheet0.png",
		"images/preingameherotextupgradeweapon-sheet0.png",
		"images/preingameherobackground-sheet0.png",
		"images/preingameherobackgroundcontent-sheet0.png",
		"images/preingameupgradewall-sheet0.png",
		"images/preingameupgradecannon-sheet0.png",
		"images/preingameupgradeplasmagun-sheet0.png",
		"images/preingameupgradespecialattack1-sheet0.png",
		"images/preingameupgradespecialattack2-sheet0.png",
		"images/preingameupgradespecialattack3-sheet0.png",
		"images/preingameupgradetextwall-sheet0.png",
		"images/preingameupgradetextcannon-sheet0.png",
		"images/preingameupgradetextplasmagun-sheet0.png",
		"images/preingameupgradetextspecialattack1-sheet0.png",
		"images/preingameupgradetextspecialattack2-sheet0.png",
		"images/preingameupgradetextspecialattack3-sheet0.png",
		"images/preingameupgradetexthp-sheet0.png",
		"images/preingameupgradetextdamage-sheet0.png",
		"images/preingameupgradetext-sheet0.png",
		"images/preingameupgradetextlevel-sheet0.png",
		"images/preingameshopgoldframe1-sheet0.png",
		"images/preingameshopgoldframe2-sheet0.png",
		"images/preingameshopgoldframe3-sheet0.png",
		"images/preingameshopgoldframe4-sheet0.png",
		"images/preingameshopgoldtext-sheet0.png",
		"images/preingamebackgroundcontent-sheet0.png",
		"images/preingamebackgroundselect-sheet0.png",
		"images/preingamewavetext-sheet0.png",
		"images/screenrotate-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/particles.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/shake.m4a",
		"media/shake.ogg",
		"media/title highlight.m4a",
		"media/title highlight.ogg",
		"media/button show.m4a",
		"media/button show.ogg",
		"media/gate close.m4a",
		"media/gate close.ogg",
		"media/title show and gate close.m4a",
		"media/title show and gate close.ogg",
		"media/title wings and gate open.m4a",
		"media/title wings and gate open.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/buy.m4a",
		"media/buy.ogg",
		"media/number.m4a",
		"media/number.ogg",
		"media/result gold.m4a",
		"media/result gold.ogg",
		"media/boss attack.m4a",
		"media/boss attack.ogg",
		"media/bullet.m4a",
		"media/bullet.ogg",
		"media/enemy attack 1.m4a",
		"media/enemy attack 1.ogg",
		"media/enemy attack 2.m4a",
		"media/enemy attack 2.ogg",
		"media/laser damage.m4a",
		"media/laser damage.ogg",
		"media/laser.m4a",
		"media/laser.ogg",
		"media/missile.m4a",
		"media/missile.ogg",
		"media/special attack 1.m4a",
		"media/special attack 1.ogg",
		"media/special attack 2.m4a",
		"media/special attack 2.ogg",
		"media/bullet damage.m4a",
		"media/missile damage.m4a",
		"media/poison damage.m4a",
		"media/bullet damage.ogg",
		"media/missile damage.ogg",
		"media/poison damage.ogg",
		"media/special attack 3.m4a",
		"media/special attack 3.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/spider bomb attack.m4a",
		"media/spider bomb attack.ogg",
		"media/boss attack poison.m4a",
		"media/boss attack poison.ogg",
		"media/boss poison recharge.m4a",
		"media/boss poison recharge.ogg",
		"media/king bat attack poison.m4a",
		"media/king bat attack poison.ogg",
		"media/void armor attack poison.m4a",
		"media/void armor attack poison.ogg",
		"media/boss show.m4a",
		"media/boss show.ogg",
		"media/boss die.m4a",
		"media/boss die.ogg",
		"media/enemy die.m4a",
		"media/enemy die.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/reset data.m4a",
		"media/reset data.ogg",
		"media/heavy.m4a",
		"media/heavy.ogg",
		"media/lsaser.m4a",
		"media/lsaser.ogg",
		"media/mius.m4a",
		"media/mius.ogg",
		"media/ok.m4a",
		"media/ok.ogg",
		"media/laser32.m4a",
		"media/laser32.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/game.m4a",
		"media/game.ogg",
		"media/gameplay.m4a",
		"media/gameplay.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"stage 1.csv",
		"stage 2.csv",
		"stage 3.csv",
		"stage 4.csv",
		"stage 5.csv",
		"stage 6.csv",
		"stage 7.csv",
		"stage 8.csv",
		"stage 9.csv",
		"stage 10.csv"
	]
}