{
	"version": 1577382156,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/btnachievement-sheet0.png",
		"images/btnleaderboard-sheet0.png",
		"images/btnads-sheet0.png",
		"images/btngoogleplay-sheet0.png",
		"images/btnaddsite-sheet0.png",
		"images/btnvideo-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/btnsound-sheet0.png",
		"images/btnsound-sheet1.png",
		"images/btnmusic-sheet0.png",
		"images/btnmusic-sheet1.png",
		"images/btnoption-sheet0.png",
		"images/btnresume-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btnkiz10-sheet0.png",
		"images/btnmore-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnretry-sheet0.png",
		"images/btnback-sheet0.png",
		"images/btnbuy-sheet0.png",
		"images/btnbuygold-sheet0.png",
		"images/btnnext-sheet0.png",
		"images/btnprev-sheet0.png",
		"images/btnshop-sheet0.png",
		"images/btnshopcoin-sheet0.png",
		"images/bg-sheet0.png",
		"images/bg-sheet1.png",
		"images/buildingright-sheet0.png",
		"images/buildingleft-sheet0.png",
		"images/parking-sheet0.png",
		"images/tree-sheet0.png",
		"images/txtgold.png",
		"images/txtlife.png",
		"images/bgpreloader-sheet0.png",
		"images/uiloading-sheet0.png",
		"images/fresult-sheet0.png",
		"images/titleresult-sheet0.png",
		"images/labelbestscore-sheet0.png",
		"images/labelscore-sheet0.png",
		"images/labelnew-sheet0.png",
		"images/transition-sheet0.png",
		"images/spr650x1024-sheet0.png",
		"images/rotatescreen-sheet0.png",
		"images/cam-sheet0.png",
		"images/uigold-sheet0.png",
		"images/uilife-sheet0.png",
		"images/uimileage-sheet0.png",
		"images/flashred-sheet0.png",
		"images/flashwhite-sheet0.png",
		"images/game-sheet0.png",
		"images/titleoption-sheet0.png",
		"images/enemybarbg-sheet0.png",
		"images/enemybar-sheet0.png",
		"images/powerup-sheet0.png",
		"images/powerup-sheet1.png",
		"images/gold-sheet0.png",
		"images/drone-sheet0.png",
		"images/trackrocket-sheet0.png",
		"images/infowarning-sheet0.png",
		"images/enemyweapon-sheet0.png",
		"images/bossweapon-sheet0.png",
		"images/char0-sheet0.png",
		"images/char1-sheet0.png",
		"images/char2-sheet0.png",
		"images/char3-sheet0.png",
		"images/char4-sheet0.png",
		"images/char5-sheet0.png",
		"images/char6-sheet0.png",
		"images/char7-sheet0.png",
		"images/char8-sheet0.png",
		"images/vfxexplosion-sheet0.png",
		"images/vfxfirechar-sheet0.png",
		"images/vfxglowchar-sheet0.png",
		"images/vfxglowenemy-sheet0.png",
		"images/vfxglowboss-sheet0.png",
		"images/vfxnitro-sheet0.png",
		"images/vfxnitro-sheet1.png",
		"images/vfxnitro-sheet2.png",
		"images/vfxpowerup-sheet0.png",
		"images/vfxgold-sheet0.png",
		"images/vfxhit-sheet0.png",
		"images/enemy0-sheet0.png",
		"images/enemy1-sheet0.png",
		"images/enemy4-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/boss-sheet0.png",
		"images/bulletchar-sheet0.png",
		"images/bulletdrone-sheet0.png",
		"images/bulletdrone-sheet1.png",
		"images/bulletrocket-sheet0.png",
		"images/bulletenemy-sheet0.png",
		"images/bulletboss-sheet0.png",
		"images/obstacle0-sheet0.png",
		"images/obstacle1-sheet0.png",
		"images/obstacle2-sheet0.png",
		"images/obstacle2-sheet1.png",
		"images/fshopchar-sheet0.png",
		"images/uibuychar-sheet0.png",
		"images/uibuychar-sheet1.png",
		"images/uibuychar-sheet2.png",
		"images/uibuygold-sheet0.png",
		"images/fshopgold-sheet0.png",
		"images/titleshop-sheet0.png",
		"images/padlock-sheet0.png",
		"images/uititle-sheet0.png",
		"images/charmenu-sheet0.png",
		"images/charmenu2-sheet0.png",
		"images/menulightflare-sheet0.png",
		"media/in game.m4a",
		"media/in game.ogg",
		"media/menu.m4a",
		"media/menu.ogg",
		"media/button prev next.m4a",
		"media/button prev next.ogg",
		"media/button.m4a",
		"media/button.ogg",
		"media/buy.m4a",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/enemy hit.m4a",
		"media/enemy hit.ogg",
		"media/lose.m4a",
		"media/lose.ogg",
		"media/not enough gold.m4a",
		"media/not enough gold.ogg",
		"media/power up.m4a",
		"media/power up.ogg",
		"media/select.m4a",
		"media/select.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/buy.ogg",
		"media/boss explode.m4a",
		"media/boss explode.ogg",
		"media/boss machine gun.m4a",
		"media/boss machine gun.ogg",
		"media/char explode.m4a",
		"media/char explode.ogg",
		"media/char hit.m4a",
		"media/char hit.ogg",
		"media/char jump.m4a",
		"media/char jump.ogg",
		"media/char weapon.m4a",
		"media/char weapon.ogg",
		"media/enemy explode.m4a",
		"media/enemy explode.ogg",
		"media/enemy weapon.m4a",
		"media/enemy weapon.ogg",
		"media/rocket.m4a",
		"media/rocket.ogg",
		"media/drone weapon.m4a",
		"media/drone weapon.ogg",
		"media/carjump2.m4a",
		"media/carjump2.ogg",
		"media/speedup.m4a",
		"media/speedup.ogg",
		"media/alert.m4a",
		"media/alert.ogg",
		"media/explosion2.m4a",
		"media/explosion2.ogg",
		"media/explosion3.m4a",
		"media/explosion3.ogg",
		"media/explosion4.m4a",
		"media/explosion4.ogg",
		"media/efecto2.m4a",
		"media/efecto2.ogg",
		"media/efecto3.m4a",
		"media/efecto3.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}