var mappings = {
    " x/2 距离": "x/2 distance",
    " z/2 距离": "z/2 distance",
    " 赛季": "Season",
    " 赛季王者奖励": "The King of the Season Award",
    " 天 ": "day ",
    " 天 可 获 得": "day can be won",
    " 永 久 ": "Forever",
    " 至 ": " to ",
    "(倒计时复活球球大小不变)": "(Countdown resurrection ball size does not change)",
    "*不试玩皮肤": "*Do not try skin",
    "*弹出登录奖励": "* pop-up login reward",
    "*弹出转盘": "*Eject carousel",
    "*登录奖励成功分享": "*Login rewards successfully shared",
    "*点击换一批": "*Click for a batch",
    "*点击开始游戏": "*Click to start the game",
    "*点击主界面皮肤": "*Click on the main interface skin",
    "*点皮肤商城试玩": "*Point Skin Mall Trial",
    "*点主界面分享": "*point main interface sharing",
    "*点主界面免费金币": "*point main interface free gold coin",
    "*点主界面免费皮肤": "* dot main interface free skin",
    "*点主界面新手特惠": "*Point main interface novice special",
    "*点主界面转盘": "*point main interface dial",
    "*分享3倍": "*Share 3 times",
    "*结算返回": "*Settlement return",
    "*进入321": "*Enter 321",
    "*进入结算": "* Enters settlement",
    "*进入匹配": "*Enter match",
    "*进入主界面": "*Enter the main interface",
    "*碾碎球球": "* crushing the ball",
    "*球球变大（分享）": "*Ball bigger (share)",
    "*球球变大（免费）": "*Ball bigger (free)",
    "*球球升阶": "* Ball upgrade",
    "*试玩皮肤": "*Try skin",
    "*视频3倍": "*Video 3 times",
    "*新人升阶": "*Newcomer upgrades",
    "*游戏30S": "*Game 30S",
    "*游戏90S": "*Game 90S",
    "*右上退出": "*Up right exit",
    "*再来一局": "* Come back again",
    "*在线时长10S": "*Online time 10S",
    "*在线时长30S": "*Online time 30S",
    ", 距离dis ：": ", distance dis :",
    ", 视域FOV ：": ", Sight FOV:",
    ",返回!": "Back!",
    "] ：移除此监听": "] : Remove this listener",
    "] 游戏加载完成": "] Game loading completed",
    "]被请出了队伍": "] was invited out of the team",
    "]加入了队伍": "] joined the team",
    "]离开了队伍": "] left the team",
    "``````````````每次显示的人：": "`````````````` Every time the person is shown:",
    "~。~好开心": "~.~ happy",
    "~~~~~~~~~~~~~~~~~~~分享失败": "~~~~~~~~~~~~~~~~~~~Share failed",
    "】,返回!": "Back!",
    "0-1距离": "0-1 distance",
    "0-2距离": "0-2 distance",
    "10次": "10 times",
    "10秒内速度降低20%": "20% slowdown in 10 seconds",
    "2018-10-1 至 2018-11-1": "2018-10-1 to 2018-11-1",
    "2-3距离": "2-3 distance",
    "2分钟内挑战高分": "challenge high score in 2 minutes",
    "3次": "3 times",
    "3分钟": "3 minutes",
    "66666分": "66666 points",
    "Jayce_天空蓝": "Jayce_sky blue",
    "Login数据`": "Login data`",
    "Master 是": "Master is",
    "S1 赛季": "S1 season",
    "S1 赛季王者奖励": "S1 Season King Award",
    "S2C 登陆成功": "S2C login succeeded",
    "S2C 接收到队伍信息 self:": "S2C received team information self:",
    "S2C 接收到击杀广播": "S2C receives a kill broadcast",
    "S2C 接收到某人被踢出信息:": "S2C received a message that someone was kicked out:",
    "S2C 接收到某人离开队伍消息": "S2C receives a message from someone leaving the team",
    "S2C 接收到某人信息 other:": "S2C receives someone's information other:",
    "S2C 强制游戏结束": "S2C Forced Game Ends",
    "S2C 收到创建队伍消息": "S2C received a message to create a team",
    "S2C 同步游戏倒计时时间": "S2C sync game countdown time",
    "S2C 玩家：[": "S2C Player: [",
    "S2C 游戏开始 : ": "S2C game starts: ",
    "S2C 有人离开游戏了：": "S2C someone left the game:",
    "SDK服务器连接超时！！！": "SDK server connection timed out!!!",
    "self_星星": "self_star",
    "socket地址错误：url=": "socket address error: url=",
    "socket连接成功": "socket connection succeeded",
    "WxSocket连接失败": "WxSocket connection failed",
    "xtexMerger 错误啦": "xtexMerger is wrong",
    "XX秒": "XX seconds",
    "阿萨德法师法撒旦法阿士大夫是否大是大非": "Assad Master Fasade Satan is a big Falcon",
    "爱什么稀罕": "What is rare?",
    "安徽": "Anhui",
    "白银1阶": "Silver Ⅰ",
    "白银2阶": "Silver Ⅱ",
    "白银3阶": "Silver Ⅲ",
    "版本更新准备好了 执行更新------------------": "Version update is ready to perform update ------------------",
    "版本太低， 创建视频失败!": "The version is too low, creating a video failed!",
    "报告长官！发现一枚机械球球，碾压之势无法阻挡~请求增援！": "Report sir! Found a mechanical ball, the crushing power can't stop ~ request reinforcements!",
    "抱歉，有玩家还未准备！": "Sorry, some players are not ready yet!",
    "抱歉，有玩家还在游戏中！": "Sorry, there are players still in the game!",
    "北京": "Beijing",
    "本次登录耗时:": "This login takes time:",
    "冰樱之雪": "Snow Cherry Snow",
    "铂金1阶": "Platinum Ⅰ",
    "铂金2阶": "Platinum Ⅱ",
    "铂金3阶": "Platinum Ⅲ",
    "不存在该队伍": "There is no such team",
    "不了，谢谢!": "No, thank you!",
    "不了，直接开始": "No, start directly",
    "不了，直接领取": "No, get it directly",
    "不再是房主了：": "No longer a homeowner:",
    "猜你喜欢数据": "Guess you like data",
    "草莓社区一姐": "Sister of Strawberry Community",
    "查看总排行": "View total ranking",
    "场景": "Scene",
    "超级梦梦梦": "Super Dreams",
    "超时处理": "Timeout Processing",
    "成功": "Success",
    "成功领取附件~": "Successful attachments~",
    "城市背景": "City Background",
    "吃": "eat",
    "吃到幸运礼包，结算时可开启~": "You can get the gift when game over",
    "吃瓜666": "eat melon 666",
    "吃瓜方六": "Eat melon square",
    "吃瓜少年": "Peasing melons",
    "吃瓜少年熊猫": "Peasing Juvenile Panda",
    "吃瓜要不六六...": "Is it worth six or six to eat melon...",
    "吃瓜要六个字": "I need six words to eat melon",
    "吃瓜一号选手...的": "Eating melon No. 1 player...",
    "吃鸡面板": "eat chicken panel",
    "吃鸡人数": "Number of chickens eaten",
    "初始化开放域": "Initialize open domain",
    "创建激励广告视频----": "Create an incentive video----",
    "打开界面获取到好友助力数据：": "Open the interface to get the friend's help data:",
    "打开免费金币": "Open free gold",
    "打开免费皮肤": "Open free skin",
    "打开皮肤": "Open the skin",
    "打开赛季奖励": "Open season reward",
    "打开限时活动": "Open limited time activity",
    "打开新手特惠": "Open a novice special",
    "打开转盘": "Open the turntable",
    "单倍领取": "Single collection",
    "单位1": "unit 1",
    "单位2": "unit 2",
    "单位3": "unit 3",
    "单位自己": "Unit yourself",
    "弹出宝箱": "Eject treasure chest",
    "当前的段位：": "current segment:",
    "当前段位：": "current segment:",
    "当前段位：白银1阶": "current segment: silver Ⅰ order",
    "当前分数，下一个分数": "current score, next score",
    "当前阶级": "current class",
    "当前人数：": "current number:",
    "当前人数10/10": "current number 10/10",
    "当前网络不稳定，是否重新匹配": "The current network is unstable, whether it is rematched",
    "当前系统：IOS": "Current system: IOS",
    "当前系统：安卓": "Current system: Android",
    "倒计时": "countdown",
    "登 录 天 数 ：": "Login days : ",
    "登陆奖励分享皮肤": "Login reward sharing skin",
    "登录奖励：": "Login reward:",
    "登录奖励成功分享": "Login rewards successfully shared",
    "第2天玩吃鸡": "Playing chicken on the Ⅱ day",
    "第3天玩吃鸡": "Playing chicken on the 3nd day",
    "第4天玩吃鸡": "Playing chicken on the 4th day",
    "第5天玩吃鸡": "Playing chicken on the 5th day",
    "第6天玩吃鸡": "Playing chicken on the 6th day",
    "第7天玩吃鸡": "Playing chicken on the 7th day",
    "第二": "second",
    "第二个零": "second zero",
    "第三": "third",
    "第一": "first",
    "第一个零": "first zero",
    "点得越快，奖励越多！": "The faster,more rewards!",
    "点击换一批": "Click for a batch",
    "点击开箱": "Click to open the box",
    "点击快捷按钮": "Click the shortcut button",
    "点击试玩看视频": "Click to play to watch the video",
    "点击组队返回": "Click to team back",
    "点击组队分享": "Click to team to share",
    "点击组队准备": "Click to team preparation",
    "段位背景": "segment background",
    "段位积分：": "Segmental points:",
    "队伍BG": "Team BG",
    "队伍已经满员了哦": "The team is full.",
    "对手的球球太强大了，快来帮我一起碾压它！": "The opponent's ball is too strong, come and help me crush it!",
    "兑换成功": "Exchange success",
    "发到群可邀请更多好友来协助你。": "Send to the group to invite more friends to assist you.",
    "发送给服务器的数据包": "Packet sent to the server",
    "发送游戏信息": "Send game information",
    "放 弃 福 利": "Abandoning welfare",
    "放弃福利": "Abandonment of welfare",
    "飞鞋成功分享": "Flying shoes successfully shared",
    "分享3次可增加1次视频进度": "Share 3 times to increase 1 video progress",
    "分享变大": "Share becomes bigger",
    "分享标记": "Share tag",
    "分享成功，3次分享能增加皮肤进度哟~": "Sharing success, 3 sharing can increase skin progress 哟~",
    "分享到群onSharGroupSuccess res 为空": "Share to group onSharGroupSuccess res is empty",
    "分享复活": "Revive",
    "分享获得": "Shared by",
    "分享开箱": "Share out of the box",
    "分享试玩成功": "Share trial success",
    "分享双倍": "Share double",
    "分享图ID": "Shared figure ID",
    "分享图点击统计结果：": "Share graph click statistics:",
    "分享图统计错误": "Share graph statistics error",
    "分享图统计发送，统计参数：": "Share graph statistics sent, statistical parameters:",
    "分享图统计请求,请求参数:": "Share graph statistics request, request parameters:",
    "分享图展示统计成功": "Share the graph to show statistical success",
    "分享图展示统计错误": "Share the graph showing statistical errors",
    "分享转动": "Sharing the rotation",
    "分享转盘次数": "Share turntable times",
    "服务器的SKEY过期了！！！": "The server's SKEY has expired!!!",
    "福建": "Fujian",
    "复活": "Revive",
    "复活成功分享": "Resurrection and successful sharing",
    "该皮肤已拥有，请换一个": "The skin is already owned, please change one",
    "改变AI阶级": "Change AI class",
    "改变玩家阶级": "Change the player class",
    "甘肃": "Gansu",
    "敢不敢吞了这座城再走？": "Don't dare to swallow the city and go?",
    "敢不敢吞了这座城再走TT": "Don't dare to swallow the city and go TT",
    "个好友帮助了你": "A friend has helped you",
    "个人信息": "Personal Information",
    "更新补偿": "Update Compensation",
    "更新服务器数据，当前活动类型免费助力": "Update server data, current activity type free help",
    "更新奖励": "Update Reward",
    "更新界面显示": "Update interface display",
    "恭喜获得三倍奖励": "Congratulations for triple reward",
    "购买成功": "Purchase success",
    "关闭": "closed",
    "关闭视频，是否观看完整：": "Close the video, watch the complete:",
    "关闭调试成功": "Close debugging successfully",
    "观看视频成功，皮肤进度增加": "Watch video successfully, skin progress increases",
    "广东": "Guangdong",
    "广东车神": "Guangdong car god",
    "广告创建失败，sdk：": "Ad creation failed, sdk:",
    "广告创建失败：错误信息：": "Ad creation failed: error message:",
    "广告未播放完毕，未获得礼包奖励": "The ad has not been played and has not received the gift package reward",
    "广告未播放完毕，未获得三倍奖励": "The ad has not been played and has not received a triple reward",
    "广告未播放完毕，未获得碎片奖励": "The ad has not been played, and no shards have been awarded",
    "广告未播放完毕，未增加次数": "The ad has not been played, no increase",
    "广告未播放完毕，无法试玩皮肤": "Ads are not playing, you can't try the skin",
    "广西": "Guangxi",
    "规则说明": "Rules Description",
    "贵州": "Guizhou",
    "哈哈哈 ： ": "Ha ha ha : ",
    "还有人没有准备好，无法开始游戏": "There are people who are not ready to start the game",
    "海点": "Sea Point",
    "海南": "Hainan",
    "毫秒": "milliseconds",
    "好友比拼来吃鸡": "Friends compete to eat chicken",
    "好友排名": "Friends Rank",
    "好友助力成功": "Friends help success",
    "好友助力分享的openid=": "Friends help share openid=",
    "好友组力": "Friends",
    "河北": "Hebei",
    "河南": "Henan",
    "黑洞会成长": "Black hole will grow",
    "黑洞皮肤": "black hole skin",
    "黑龙江": "Heilongjiang",
    "湖北": "Hubei",
    "湖南": "Hunan",
    "缓存出错！": "Cache error!",
    "幻影皮卡丘君": "Phantom Pikachu Jun",
    "黄金1阶": "Gold Ⅰ",
    "黄金2阶": "Gold Ⅱ",
    "黄金3阶": "Gold Ⅲ",
    "活动开启中，活动ID=": "Event is on, activity ID=",
    "活动时间：": "Event time:",
    "活动时间：2018.9.23 - 2018.9.25": "Event time: 2011.9.23 - 2018.9.25",
    "活动时间为：id=": "Event time is: id=",
    "火球降临，碾压万物生灵涂炭，快来拯救苍生吧！": "The fireball is coming, crushing all things and living with charcoal, come and save the people!",
    "获得": "Get",
    "获得第一名": "Get the first place",
    "获得开局变大": "Get the start and get bigger",
    "获得匹配的玩家数据": "Get matching player data",
    "获取到好友助力数据：": "Get friends to help data:",
    "获取分享图": "Get sharing map",
    "获取服务器排行榜信息,res=": "Get server leaderboard information, res=",
    "获取排行数据": "Get ranking data",
    "击杀了": "killed",
    "击杀数": "kill number",
    "激励视频广告关闭了": "Incentive video ads are closed",
    "吉林": "Jilin",
    "继续游戏": "Continue",
    "加载完成开始播放视频": "Load completed to start playing video",
    "检查更新11111111111": "Check for updates 11111111111",
    "江苏": "Jiangsu",
    "江西": "Jiangxi",
    "将获得价值                   皮肤一个": "will get a skin worth",
    "奖励": "Reward",
    "角度X ：": "Angle X:",
    "角度Y : ": "Angle Y : ",
    "阶级:": "Class:",
    "接收到的游戏信息": "Received game information",
    "接受到匹配到的数据": "Accepted matching data",
    "结束游戏": "End game",
    "结算返回（吃鸡）": "Settlement return (eat chicken)",
    "结算分享": "Billing Sharing",
    "结算分享（吃鸡）": "Settlement Sharing (Eating Chicken)",
    "结算看视频": "Settlement watching video",
    "结算看视频（吃鸡）": "Settlement watching video (eat chicken)",
    "结算炫耀（吃鸡）": "Settlement show off (eat chicken)",
    "解析失败": "parsing failed",
    "今 日 奖 励": "Today's Awards",
    "今日充能已达上限!": "Today's charge has reached the upper limit!",
    "今日次数已用完，请明日再来": "Today's number has been used up, please come back tomorrow",
    "今日之内不再显示": "No longer displayed today",
    "今天观看视频的时间和次数：": "Time and number of videos watched today:",
    "金币": "Gold",
    "金币x": "Gold x",
    "金币X": "Gold X",
    "金币x100": "Gold x100",
    "金币不足": "Gold inadequate",
    "进度": "Progress",
    "进入结算（吃鸡）": "Enter settlement (eat chicken)",
    "进入结算_经典模式": "Enter settlement_classic mode",
    "进入匹配": "Enter match",
    "进入匹配（吃鸡）": "Enter match (eat chicken)",
    "进入游戏321（吃鸡）": "Enter game 321 (eat chicken)",
    "进入游戏参数:": "Enter game parameters:",
    "进入组队界面": "Enter the team interface",
    "精美皮肤！": "Beautiful skin!",
    "静态类": "static class",
    "开放域：heigh:": "Open domain: heigh:",
    "开放域：width:": "open domain: width:",
    "开放域资源加载完成": "Open domain resource loading completed",
    "开局体积变大": "The opening volume becomes larger",
    "开局增加2倍的大小": "The opening is increased by 2 times the size",
    "开启调试成功": "Start debugging successfully",
    "开始请求登陆": "Start requesting login",
    "开始请求匹配": "Start request matching",
    "开始微信登录！": "Start WeChat login!",
    "开始游戏": "Start the game",
    "开始游戏（吃鸡）": "Starting the game (eat chicken)",
    "看视频获得": "Look at the video",
    "看视频试玩成功": "Look at the video demo",
    "可兑换": "Exchangeable",
    "快点开啊，我都等到海枯石烂了~": "Come on, I will wait until the sea is dead.",
    "快点开呀，我都等到海枯石烂了QAQ": "Come on, I will wait until the sea is dead, QAQ",
    "快捷键": "shortcut",
    "快捷语": "Short Word",
    "快进队，来体验碾压一座城的乐趣~": "Fast into the team, to experience the fun of crushing a city~",
    "快去邀请好友获得奖励吧！": "Go and invite your friends to get rewards!",
    "蓝底": "blue bottom",
    "累 积 登 录 x 天 可 获 得": "Accumulative registration for x days can be obtained",
    "累 计 登 录 ": "Accumulating Login",
    "历史的最高段位：": "The highest position of history:",
    "立即邀请": "Invitation now",
    "连接WEBSOCKET：：：：": "Connect WEBSOCKET::::",
    "连接WXSOCKET：：：：": "Connect WXSOCKET::::",
    "连接WXS失败，请检查服务器状态": "Failed to connect to WXS, please check server status",
    "连接分区服务器成功:": "Connection to partition server succeeded:",
    "连接服务器超时，请重启游戏": "Connection server timed out, please restart the game",
    "连接服务器成功:": "Connected to the server successfully:",
    "连接服务器失败，请重启游戏": "Failed to connect to the server, please restart the game",
    "连接失败， 请检查服务器状态": "Connection failed, please check server status",
    "连续三天登录游戏": "Login game for three consecutive days",
    "链接WXS成功": "Link WXS Success",
    "链接成功": "Link success",
    "辽宁": "Liaoning",
    "聊天BG": "chat BG",
    "聊天输入BG": "chat input BG",
    "领 取": "Learn",
    "领取奖励": "Receive reward",
    "领取皮肤成功，去皮肤界面使用吧~": "Successfully, use it now!",
    "领取失败": "Failed to receive",
    "六泫": "Six 泫",
    "没有该皮肤的模型：": "Model without this skin:",
    "没有该皮肤的模型：Ball_": "Model without this skin: Ball_",
    "没有邮件~": "No mail~",
    "每5分钟刷新排名，赛季结束将重置积分": "",
    "每次邀请好友首次进入游戏可领取": "Every time you invite a friend to enter the game for the first time",
    "每次邀请好友首次进入游戏可领取100金币": "Every time you invite a friend to enter the game for the first time, you can receive 100 gold coins",
    "每天最多充能    次": "Maximum charge per day",
    "魅蓝星舰": "Charming Blue Starship",
    "萌狐狸": "Fox",
    "萌萌酱": "Lovelyer",
    "懵萌蒙梦": "lovely",
    "免 费 领 取": "Free access",
    "免费金币邀请": "Free Gold Coin Invitation",
    "免费皮肤试玩": "Free Skin Trial",
    "免费皮肤邀请": "Free Skin Invitation",
    "免费转盘次数": "Free turntable times",
    "免费转一次": "Free once",
    "秒": "second",
    "秒后自动开始": "Automatically start after seconds",
    "秒后自动离开队伍": "Automatically leave the team after seconds",
    "名！碾压之势无法阻挡~": "Name! The crushing power can't stop ~",
    "名字背景": "Name Background",
    "明天再来免费抽吧！": "Get free draws tomorrow!",
    "魔法": "magic",
    "内蒙古": "Inner Mongolia",
    "你好，很高兴和你们一起玩~": "Hello, I am very happy to play with you~",
    "你好，很高兴能和你们一起玩！": "Hello, I am very happy to play with you!",
    "碾碎 : 0个球球": "Crushing: 0 balls",
    "碾碎对手": "Crushing opponent",
    "碾碎了你": "Crushed you",
    "您被请离了队伍": "You are asked to leave the team",
    "您的SDK不是最新版本，请尽快升级！": "Your SDK is not the latest version, please upgrade as soon as possible!",
    "您确定要离开队伍吗？": "Are you sure you want to leave the team?",
    "您确定要踢出该队员吗？": "Are you sure you want to kick the player?",
    "您说话太快了，请等一会吧~": "You are talking too fast, please wait a moment~",
    "您已经被请出队伍": "You have been asked to leave the team",
    "宁夏": "Ningxia",
    "排行榜即将超越": "The leaderboard is about to surpass",
    "排行榜截图分享失败": "Leader screenshot sharing failed",
    "排名": "Rank",
    "皮肤界面看视频": "Skin interface to watch video",
    "皮肤界面看视频成功": "Skin interface to watch video success",
    "皮肤界面试玩": "Skin Interface Trial",
    "皮肤名称": "Skin name",
    "匹配到的数据：": "Matched data:",
    "七度阳光": "Seven degrees of sunshine",
    "切换吃鸡模式": "Switch to eat chicken mode",
    "切换经典模式": "Switch classic mode",
    "且每位好友每天最多助力你    次": "And every friend can help you up to every day",
    "亲爱的玩家，您上赛季段位达到$，恭喜您获得赛季奖励，请查收，再接再厉哟！": "Dear players, you reached $ in the last season, congratulations on winning the season, please check and keep up!",
    "亲爱的玩家，游戏于$进行版本更新，给您带来的不便请谅解，特此赠送更新奖励，请及时领取！": "Dear players, the game is updated in version. Please forgive us for any inconvenience. Please give us an update reward, please get it in time!",
    "青海": "Qinghai",
    "青铜1阶": "Bronze Ⅰ",
    "青铜3阶": "Bronze Ⅲ",
    "青铜一阶": "Bronze Ⅰ",
    "请您及时准备，否则": "Please prepare in time, otherwise",
    "请求耗时:": "Request time consuming:",
    "请求离开游戏了": "Request to leave the game",
    "请选取一款喜爱的皮肤吧！": "Please choose a favorite skin!",
    "请选择一款皮肤": "Please choose a skin",
    "球球": "ball",
    "球球变大（分享）": "Ball becomes bigger (share)",
    "渠道信息channel:": "Channel information channel:",
    "全国排行请求太频繁": "National ranking request is too frequent",
    "全球最强": "The world's strongest",
    "全员已准备，等待队长开始游戏，或": "All members are ready, waiting for the captain to start the game, or",
    "群id:": "group id:",
    "群分享的参数：": "Group sharing parameters:",
    "群里排第几，戳这里就知道，记住用力戳这里": "The first few in the group, you will know here, remember to force it here.",
    "群排行": "group ranking",
    "人, 详细数据：": "People, detailed data:",
    "人数": "number of people",
    "任": "Ren",
    "任意人数都能直接开始匹配其他玩家": "Any number of people can start matching other players directly",
    "赛季结束后可领取奖励": "Available after the season",
    "赛季结束可获得赛季奖励，赛季积分将会被重置": "The season will be awarded at the end\nof the season and the season points will be reset.",
    "赛季重置，积分清空！！！": "Season reset, points cleared!",
    "三倍奖励": "Triple reward",
    "山东": "Shandong",
    "山西": "Shanxi",
    "陕西": "Shaanxi",
    "上报完成························": "Report completed...",
    "上传SDK数据": "Upload SDK data",
    "上海": "Shanghai",
    "上一个激励视频还没看完呢": "The last incentive video hasn't finished reading yet",
    "设置皮肤": "Setting the skin",
    "声音": "sound",
    "省内排行请求太频繁": "The province's ranking request is too frequent",
    "失败": "Failed",
    "时长": "time",
    "使 用": "Use",
    "使用": "Use",
    "使用中": "in use",
    "事件[": "Event [",
    "试玩皮肤状态：1 可以试玩  2 看视频": "Try skin status: 1 can try 2 watch video",
    "视频": "video",
    "视频变大": "Bigger",
    "视频标记": "video tag",
    "视频获得": "Video Get",
    "视频加载失败！！": "Video failed to load!!",
    "视频加载中...": "Video loading...",
    "视频开箱": "Video out of the box",
    "视频类型": "Video Type",
    "视频转动": "Video",
    "视频转盘次数": "Video turntable times",
    "是 否 退 出 本 局 游 戏 ？": " Is it out of this game ? ",
    "是否看完": "Is it finished?",
    "是否显示": "Is it displayed",
    "手指滑动起来吧": "Pipe your finger up",
    "数据解密错误": "Data decryption error",
    "数量:20": "Quantity: 20",
    "刷新太快了，请稍后再试": "It's too fast, please try again later",
    "双倍得分：": "Double score:",
    "双倍奖励": "Double reward",
    "双倍时间：10秒": "Double time: 10 seconds",
    "四川": "Sichuan",
    "四周出现了一批神秘宝箱~": "A bunch of mysterious treasure chests appeared around",
    "俗不可耐": "Vulgar",
    "碎片不足": "Insufficient fragmentation",
    "所邀请的玩家必须是之前未进入过游戏才能计数。": "Invited players must be counted before they have entered the game.",
    "提示": "tip",
    "提示语": "prompt",
    "体积最大": "Maximum volume",
    "天津": "Tianjin",
    "挑选一款皮肤": "Choose a skin",
    "跳 过": "jumped over",
    "跳转点击成功": "Click to click successfully",
    "跳转展示成功": "Jump display success",
    "同步服务器数据，时间：": "Sync server data, time:",
    "同意授权才可查看排名信息": "Agree to authorize to view ranking information",
    "头衔": "title",
    "头像数据": "avatar data",
    "推荐一款非常好玩的游戏，只需动动手指就变得大大大！根本停不下来！": "Recommended for a very fun game, just make a big move with your finger! It won't stop!",
    "推送免费皮肤": "Push free skin",
    "推送新手特惠": "Pushing novice deals",
    "推送转盘": "Pushing turntable",
    "退 出 将 没 有 结 算 奖 励": "There will be no award",
    "退出匹配": "Exit match",
    "退出游戏": "Exit",
    "吞无不胜": "Invincible",
    "挖矿小队啊": "Mining team",
    "完成新手特惠": "Complete the novice offer",
    "玩家的历史的最高段位：": "The highest segment of the player's history:",
    "玩家名字": "Player Name",
    "玩家名字123": "Player Name 123",
    "万": "10,000",
    "王者1阶": "King's Ⅰ",
    "王者2阶": "King's Ⅱ",
    "王者3阶": "King's Ⅲ",
    "网络出错，已回到组队界面": "Network error, has returned to the team interface",
    "网络出现了点问题，请重启再试一次": "There is a problem with the network, please try again and try again",
    "网络连接中...": "Network connection...",
    "微信登录成功，": "Wechat login is successful,",
    "微信登录失败~！": "Wechat login failed ~!",
    "微信更新信息， ": "WeChat update information,",
    "未获得": "not obtained",
    "未获得排名奖励": "No ranking reward",
    "未连接上服务器，请检测您的网络": "Not connected to the server, please check your network",
    "未完成任务不能领取": "Unfinished tasks cannot be received",
    "未拥有（": "Not owned (",
    "我的客户端中生成好了玩家": "The player is built in my client",
    "我控制球球可以碾压一座城！你也一起来碾压一切吧！": "I can control a ball to crush a city! You can also crush everything together!",
    "我若爱便已深爱": "If I love, I will love it",
    "我在联机对战中获得第": "I got the first in the online game",
    "我自己": "Myself",
    "无  敌": "Invincible",
    "五角星": "Pentagram",
    "系统已经自动开始游戏": "The system has started the game automatically",
    "下方按钮": "Bottom button",
    "下局球球": "The next ball",
    "限时活动分享": "Limited time sharing",
    "限时活动看视频": "Limited time to watch video",
    "限时活动看视频成功": "Limited time to watch video success",
    "新matser：": "New matser:",
    "新疆": "Xinjiang",
    "新手特惠看视频": "Novice specials to watch videos",
    "新手特惠领奖": "Novice Specials Award",
    "星耀1阶": "Stars Ⅰ",
    "星耀2阶": "Stars Ⅱ",
    "星耀3阶": "Stars Ⅲ",
    "性能面板开关": "performance panel switch",
    "炫    耀": "Show",
    "炫耀": "Show",
    "炫耀成功": "Show off success",
    "炫耀分享": "Show off sharing",
    "邀请": "Invitation",
    "邀请好友助力或看视频能为皮肤充能，": "Invite a friend to help or watch the video to recharge the skin,",
    "邀请人数": "Invited person",
    "要观看完视频哦~": "To watch the video~",
    "一二三四五六七八九十": "1 2 3 4 5 6 7 8 9 ",
    "已达今日金币奖励次数上限": "The limit of the number of gold coins awarded today",
    "已获得该阶奖励": "has received this award",
    "已经离开队伍": "has left the team",
    "已领取活动皮肤，快去皮肤里使用吧": "You have received active skin, go to the skin and use it",
    "已试玩": "Tryed to play",
    "以下皮肤任选其一": "One of the following skins",
    "由于您未及时准备，已被系统请出队伍": "Because you have not prepared in time, you have been asked to leave the team",
    "邮 件 只 保 留 7 天": "Mail only stays for 7 days",
    "邮件消息:正在加载": "Mail Message: Loading",
    "邮箱": "mailbox",
    "游戏30S（吃鸡）": "Game 30S (eat chicken)",
    "游戏60S": "Game 60S",
    "游戏马上开始！": "The game starts right away!",
    "游戏中断线": "game break line",
    "游戏中任意位置观看": "Watch video for",
    "有新版本需要更新": "There is a new version that needs to be updated",
    "右边背景": "right background",
    "云南": "Yunnan",
    "再充能         次即可获得": "Recharge once to get",
    "再等等，马上就开，别着急：）": "Let's wait, open right away, don't worry:)",
    "再等等，马上就开，别着急~": "Let's wait, open right away, don't worry~",
    "再邀请      位玩家即可获得": "Re-inviting players to get",
    "增加机器人": "Add robot",
    "赠送您": "Give you",
    "展示统计": "Showing statistics",
    "这是一段测试文字，这是一段测试文字，这是一段测试文字，这是一段测试文字": "This is a test text. This is a test text. This is a test text. This is a test text.",
    "浙江": "Zhejiang",
    "正在": "Being",
    "正在打扫场景": "Sweeping the scene",
    "正在搜索全球球球": "Searching players",
    "只有队长才能开始游戏": "Only the captain can start the game",
    "中间的两个点": "Two points in the middle",
    "中间玩家地板BG": "Intermediate player floor BG",
    "重庆": "Chongqing",
    "重新开局": "Restart",
    "重新匹配": "Rematch",
    "转盘翻倍分享": "Carousel doubles sharing",
    "转盘翻倍视频": "Carousel doubles video",
    "转盘增加金币：": "Carousel adds gold coins:",
    "转盘增加皮肤，皮肤id=：": "The turntable adds skin, skin id=:",
    "转盘转动次数": "Number of turns of the turntable",
    "准备": "Prepare",
    "钻石1阶": "Diamond Ⅰ",
    "钻石2阶": "Diamond Ⅱ",
    "钻石3阶": "Diamond Ⅲ",
    "钻石一阶": "Diamond Ⅰ",
    "最近点": "Recent point",
    "最远点": "the farthest point",
    "左边背景": "left background",
    "(立即复活)": "(immediately)",
    "10人": "10 people",
    "被": "being",
    "成功使用飞鞋，移速": "Successful use of flying shoes, speed ",
    "吃瓜少年等等": "Put melon boy, etc.",
    "吃鸡攻略": "Eating Chicken Raiders",
    "初始拥有": "Initial ownership",
    "单位": "units",
    "当前微信版本不支持开放数据域": "The current WeChat version does not support open data fields",
    "登录失败，可能是网络错误或者服务器发生异常": "Login failed, it could be a network error or an exception occurred on the server",
    "点击试玩分享": "Click to try sharing",
    "点击游戏模式": "Click on game mode",
    "段位保护": "segment protection",
    "队伍": "Team",
    "分享的参数：": "Shared parameters:",
    "该次数已用完，试试其他方式吧": "This number has been used up, try other methods",
    "广告未播放完毕，未获得双倍奖励": "The ad has not been played and has not received double reward",
    "还未登录成功": "Not logged in successfully",
    "行楷": "Action",
    "行楷-简": "行楷-简",
    "黑体-简": "Bold body - Jane",
    "活动获得": "Activity acquisition",
    "获得排名": "Get the ranking",
    "获得碎片奖励": "Get Fraud Award",
    "获取微信用户信息失败，请检查网络状态": "Failed to get WeChat user information, please check the network status",
    "坚持就是胜利": "Perseverance is victory",
    "阶级:1": "Class: 1",
    "接受到分享参数 openId：": "Accept the sharing parameter openId:",
    "金币购买": "Gold purchase",
    "经典模式第一": "Classic mode first",
    "敬请期待": "Please look forward to",
    "开始": "Beginning",
    "开始重新匹配": "Start rematching",
    "看视频": "Video",
    "累计登陆": "Accumulative landing",
    "累计分享": "Shared Share",
    "立即领取": "Get it immediately",
    "领取奖励成功~": "Receive rewards successfully~",
    "名字": "name",
    "匿名好友": "anonymous friend",
    "碾碎对手 ": "Crushing opponents ",
    "碾压得分：": "Crushing score:",
    "碾压对手：": "Crushing opponents:",
    "皮肤ID": "skin ID",
    "普 通": "Popular",
    "青铜2阶": "Bronze Ⅱ",
    "请升级微信": "Please upgrade WeChat",
    "求助好友": "Helping friends",
    "球球成长": "Ball growth",
    "球球缩小": "ball shrinking",
    "球球移速": "Ball speed ",
    "取消准备": "Cancel preparation",
    "全 部": "All",
    "确 定": "Confirm",
    "让你们见识一下我的厉害！": "Let you see my power!",
    "赛季王者奖励": "The King of the Season Award",
    "神秘宝箱": "Mystery Treasure Chest",
    "剩余球球：": "Remaining ball:",
    "剩余球球：10": "Remaining ball: 10",
    "史 诗": "Legendary",
    "试 玩": "Try",
    "试玩成功": "Trial success",
    "视频领取": "Video",
    "数量:": "Quantity:",
    "碎片兑换": "Fringe Exchange",
    "天）": "days)",
    "天登录奖励": "day login reward",
    "吞了": "swallowed",
    "玩家名字七个字": "The player's name is seven words",
    "微信更新管理出错": "WeChat update management error",
    "未拥有": "Not owned",
    "未知消息 消息号：": "Unknown message Message number:",
    "我马上就能领取免费皮肤了，快来帮帮我，就点一下~": "I will get free skin right away. Come and help me, just click~",
    "无皮肤特性": "No skin characteristics",
    "稀 有": "Rare",
    "新手特惠分享成功": "Novice special sharing success",
    "炫耀成功!": "Show success!",
    "炫耀得分": "Show score",
    "压碎了T-T": "Crushed T-T",
    "邀请好友": "Invite friends",
    "一二三四五六...": "One two three four five six...",
    "已获得4款特惠皮肤，不能再次领取哦": "There are 4 special skins that can't be picked up again",
    "已经领取该天的奖励": "The reward for the day has been received",
    "永久": "Permanent",
    "游": "Swim",
    "游客": "Visitors",
    "再来一局": "Again",
    "增加三倍奖励": "Increase triple reward",
    "争取第一": "Strive for the first",
    "正在尝试重新连接服务器": "Trying to reconnect to the server",
    "正在努力加载": "Trying to load",
    "正在装扮城市": "Preparing the city",
    "直接开始": "Direct start",
    "转盘增加皮肤碎片，皮肤碎片id=：": "The turntable adds skin debris, skin debris id=:",
    "准备了，准备了，磨磨唧唧干啥呢= =": "Prepared, prepared, grinded and dried up = =",
    "组队BG": "team BG",
    "2分钟": "2 minutes",
    "变大": "bigger",
    "标题": "Title",
    "不了，谢谢": "No, thank you",
    "分享成功": "Sharing success",
    "分享领取": "Share collection",
    "该皮肤已经可以试玩了": "The skin is ready to play",
    "黑体": "black body",
    "获得奖励": "Get rewards",
    "金币不足，欢乐转盘得金币哟~": "Gold is not enough!",
    "开局碾压小建筑群，成长更快哦~": "Crush small buildings, grow faster~",
    "每个皮肤每天只能试玩一次！": "Every skin can only be played once a day!",
    "每天最多试玩5个皮肤": "Try up to 5 skins per day",
    "名字2": "Name 2",
    "您看视频太频繁了，休息一下再来吧~": "You watch the video too often, take a break and come back~",
    "取消": "Cancel",
    "确定": "OK",
    "赛季奖励": "season reward",
    "玩家[": "Player [",
    "微信登录失败！！": "Wechat login failed!!",
    "未知省份": "unknown provinces",
    "已领取": "Received",
    "当前成功率": "current success rate",
    "广告未播放完毕，无法获得奖励": "Ads are not playing and cannot be rewarded",
    "天": "days",
    "已拥有（剩余": "has owned (remaining",
    "分享失败！": "Share failed!",
    "系统消息": "System Message",
    "次": "times",
    "吨": "T",
    "发送快捷内容": "Send Quick Content",
    "金币X50": "Gold X50",
    "已拥有": "Already owned"
};

window.__replace_string = function(str, lb) {
    /*
    // 这里可以根据文字匹配加入断点，以便于查找响应元素，以及调整文字位置等...
    if(str === '游戏加载中...'){
        debugger;
    } */
    // 非字符串交给游戏逻辑处理
    if (!str || !str.replace) {
        return str;
    }
    var _oldstr = str;

    // 优先从map中获取相应文本的翻译
    str = mappings[str] || str;

    // 替换"500金币"为"500 Gold"，数字提取参考正则表达式的分组功能
    str = str.replace(/^(\d+)金币$/, function(str, n) {
            return n + ' Gold';
        })
        .replace(/^\+(\d+)金币$/, function(str, n) { // 替换"+500金币"为"+500 Gold"
            return '+' + n + ' Gold';
        });

    // 打印原文字以及转换后的文字
    console.log(_oldstr, ' \t >>>: ', str)
    return str;
}
