{
	"version": 1518185273,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/roata-sheet0.png",
		"images/roata-sheet1.png",
		"images/umbraroata-sheet0.png",
		"images/knife_icon_close-sheet0.png",
		"images/knife_icon_close-sheet1.png",
		"images/stage_icons_-sheet0.png",
		"images/knife-sheet0.png",
		"images/knife-sheet1.png",
		"images/alb-sheet0.png",
		"images/particles.png",
		"images/roata_bucata_-sheet0.png",
		"images/roata_bucata_-sheet1.png",
		"images/roata_bucata_-sheet2.png",
		"images/apple1-sheet0.png",
		"images/apple_jumate-sheet0.png",
		"images/checkexist-sheet0.png",
		"images/apple2-sheet0.png",
		"images/cutitinfipt1-sheet0.png",
		"images/boss_intro_-sheet0.png",
		"images/boss_intro_-sheet1.png",
		"images/boss_intro_-sheet2.png",
		"images/boss_intro_-sheet3.png",
		"images/boss_intro_-sheet4.png",
		"images/boss_intro_-sheet5.png",
		"images/boss_intro_-sheet6.png",
		"images/boss_intro_-sheet7.png",
		"images/boss_intro_-sheet8.png",
		"images/boss_intro_-sheet9.png",
		"images/boss_intro_-sheet10.png",
		"images/boss_intro_-sheet11.png",
		"images/boss_intro_-sheet12.png",
		"images/boss_intro_-sheet13.png",
		"images/boss_intro_-sheet14.png",
		"images/boss_intro_-sheet15.png",
		"images/boss_intro_-sheet16.png",
		"images/boss_intro_-sheet17.png",
		"images/boss_intro_-sheet18.png",
		"images/boss_intro_-sheet19.png",
		"images/boss_intro_-sheet20.png",
		"images/boss_intro_-sheet21.png",
		"images/boss_intro_-sheet22.png",
		"images/boss_intro_-sheet23.png",
		"images/boss_intro_-sheet24.png",
		"images/boss_intro_-sheet25.png",
		"images/boss_intro_-sheet26.png",
		"images/boss_1_text-sheet0.png",
		"images/boss_1_text-sheet1.png",
		"images/bg_shop-sheet0.png",
		"images/boss_knife_-sheet0.png",
		"images/hud-sheet0.png",
		"images/asfgas-sheet0.png",
		"images/boss_1_icon_defeat-sheet0.png",
		"images/bosses_defeated_-sheet0.png",
		"images/unlock_now-sheet0.png",
		"images/lumina-sheet0.png",
		"images/knifeshowcase-sheet0.png",
		"images/knifeshowcase-sheet1.png",
		"images/back-sheet0.png",
		"images/reward-sheet0.png",
		"images/reward-sheet1.png",
		"images/shop-sheet0.png",
		"images/shop-sheet1.png",
		"images/play-sheet0.png",
		"images/hit-sheet0.png",
		"images/knife2-sheet0.png",
		"images/knife_logo-sheet0.png",
		"images/rounded-sheet0.png",
		"images/indicatorselected-sheet0.png",
		"images/indicatorselected-sheet1.png",
		"images/restart-sheet0.png",
		"images/finish_points-sheet0.png",
		"images/back_home-sheet0.png",
		"images/sound_button_off-sheet0.png",
		"images/sound_button_off-sheet1.png",
		"images/unlock_bg-sheet0.png",
		"images/x_button-sheet0.png",
		"images/equip-sheet0.png",
		"images/boss_1_text_unlock-sheet0.png",
		"images/boss_1_text_unlock-sheet1.png",
		"images/boss_1_text_unlock-sheet2.png",
		"images/sunetroata-sheet0.png",
		"images/sunetroata-sheet1.png",
		"images/sprite-sheet0.png",
		"images/particulemere.png",
		"images/loadingcopy-sheet0.png",
		"media/boss se sparge.m4a",
		"media/boss se sparge.ogg",
		"media/button tap sound.m4a",
		"media/button tap sound.ogg",
		"media/cutit lovit lemn.m4a",
		"media/cutit lovit lemn.ogg",
		"media/incepe batalie boss.m4a",
		"media/incepe batalie boss.ogg",
		"media/lovit alt cutit.m4a",
		"media/lovit alt cutit.ogg",
		"media/lovit boss.m4a",
		"media/lovit boss.ogg",
		"media/spart lemn 2.m4a",
		"media/spart lemn 2.ogg",
		"media/spart lemn.m4a",
		"media/spart lemn.ogg",
		"media/batut_boss.m4a",
		"media/batut_boss.ogg",
		"media/taiat_fruct.m4a",
		"media/taiat_fruct.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"animate.min.css"
	]
}